In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
%pip install six
%pip install scikit-learn
## In random forest we can plot a Decision tree present in Random forest
import sklearn
from sklearn.tree import export_graphviz
import pydotplus
import six
#sklearn.externals.six = six
#print(sklearn.externals.six)
import six
import sys
sys.modules['sklearn.externals.six'] = six
from sklearn.externals.six import StringIO
%conda install python-graphviz
%conds install pydotplus

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - python-graphviz


The following NEW packages will be INSTALLED:

  cairo              pkgs/main/win-64::cairo-1.16.0-he04af86_2 None
  expat              pkgs/main/win-64::expat-2.4.9-h6c2663c_0 None
  fribidi            pkgs/main/win-64::fribidi-1.0.10-h62dcd97_0 None
  getopt-win32       pkgs/main/win-64::getopt-win32-0.1-h2bbff1b_0 None
  glib               pkgs/main/win-64::glib-2.69.1-h5dc1a3c_1 None
  graphite2          pkgs/main/win-64::graphite2-1.3.14-hd77b12b_1 None
  graphviz           pkgs/main/win-64::graphviz-2.50.0-hdb8b0d4_0 None
  gts             


EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3


UsageError: Line magic function `%conds` not found.


In [3]:
data=pd.read_csv("D:\Self\Data Science\Random Forest (R)\Assignment\Fraud_check.csv")
data

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [4]:
# Converting the taxable income variable to bucketing
data["income"]="<=30000"
data.loc[data["Taxable.Income"]>=30000,"income"]="Good"
data.loc[data["Taxable.Income"]<=30000,"income"]="Risky"

In [5]:
#dropping the Taxable income Variable
data.drop(["Taxable.Income"],axis=1,inplace=True)

In [6]:
data.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population","Work.Experience":"experience","Urban":"urban"})

undergrad   marital  population  experience urban income
0          NO    Single       50047          10   YES   Good
1         YES  Divorced      134075          18   YES   Good
2          NO   Married      160205          30   YES   Good
3         YES    Single      193264          15   YES   Good
4          NO   Married       27533          28    NO   Good
..        ...       ...         ...         ...   ...    ...
595       YES  Divorced       39492           7   YES   Good
596       YES  Divorced       55369           2   YES   Good
597        NO  Divorced      154058           0   YES   Good
598       YES   Married      180083          17    NO   Good
599        NO  Divorced      158137          16    NO   Good

[600 rows x 6 columns]

In [7]:
le=preprocessing.LabelEncoder()
for column_name in data.columns:
    if data[column_name].dtype==object:
        data[column_name]=le.fit_transform(data[column_name])
    else:
        pass

In [8]:
x=data.iloc[:,0:5]
y=data.iloc[:,5]

In [9]:
colnames=list(data.columns)
predictors=colnames[0:5]
target=colnames[5]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y)

In [11]:
model=RF(n_jobs=3,n_estimators=15,oob_score=True,criterion="entropy")
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=15, n_jobs=3,
                       oob_score=True)

In [12]:
model.n_classes_

2

In [13]:
model.n_features_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:103: FutureWarning: Attribute `n_features_` was deprecated in version 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
  warnings.warn(msg, category=FutureWarning)


5

In [14]:
model.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=2119775853),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1311862883),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1980130607),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1750413105),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=230868192),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1203155395),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1043739194),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=806115734),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
        

In [15]:
model.classes_

array([0, 1])

In [16]:
model.n_outputs_

1

In [17]:
model.oob_score_

0.7238095238095238

In [18]:
#Prediction on train Data
prediction=model.predict(x_train)
prediction

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [19]:
accuracy=accuracy_score(y_train,prediction)
accuracy

0.9880952380952381

In [20]:
np.mean(prediction==y_train)

0.9880952380952381

In [21]:
confusion=confusion_matrix(y_train,prediction)
confusion

array([[333,   0],
       [  5,  82]], dtype=int64)

In [22]:
pred_test=model.predict(x_test)
pred_test

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0])

In [23]:
acc_test=accuracy_score(y_test,pred_test)
acc_test

0.7388888888888889

In [24]:
tree=model.estimators_[5]
tree

DecisionTreeClassifier(criterion='entropy', max_features='auto',
                       random_state=1203155395)

In [25]:
dot_data=StringIO()
export_graphviz(tree,out_file=dot_data,filled=True,rounded=True,feature_names=predictors,class_names=target,impurity=False)

In [26]:
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
graph